name: demos
favicon: null
layout_spectrum: 0.15796
typography_spectrum: 0.95105
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#18181a'
    - '#bfd2e0'
    - '#3f5062'
    - '#6c869d'
    - '#fefefe'
  brandStrength: 0.25
  lightness: 0.25
  saturation: 0.125
  rhythmicContrast: 0.45022126426920295
purpose: []
